### ISSUE TITLE
[Feature Request] Remove SMS registration in NewNode messenger

### ISSUE THREAD

**Issue by kovalensky** [clostra/newnode#141]
The very idea of registering via SMS is not the most successful, I can't receive an SMS, no matter how many times I try, to use and give feedback about the app. And if it would have come, then the next day, say after the protests, gov found me guilty for using the application. It is impossible to combine privacy with such a function as sms.

In case if there's a power outage, then there could be no cell network with internet, and in this case people would try to send apk of app to each other, which wouldn't work in case of sms need with internet.

There's no feedback group as f.e. Telegram group to contact with devs, that's why I had to come to Github.

**Comment by kovalensky** [comment]
Fixed

**Comment by ManuLinares** [comment]
This isn't fixed. SMS is the only registration option in iOS and it doesn't work.
